.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sugarchain_qt test_sugarchain_qt
clean: FORCE
	$(MAKE) -C .. sugarchain_qt_clean test_sugarchain_qt_clean
check: FORCE
	$(MAKE) -C .. test_sugarchain_qt_check
sugarchain-qt sugarchain-qt.exe: FORCE
	 $(MAKE) -C .. sugarchain_qt
apk: FORCE
	$(MAKE) -C .. sugarchain_qt_apk
